config/routes.rb
Rails.application.routes.draw do

  resources :subjects do |s|
    member do
      get :activate
      get :deactivate
    end
    resources :groups do |g|
      resources :instructor_answers
      resources :posts do |p|
        resources :discussions
      end
    end
    resources :topics
  end
  root to: 'subjects#index'
  devise_for :users
  resources :users

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :Group

  validates :title, presence: true, uniqueness: true, length:
    {
      minimum: 1, 
      maximum: 20,
      tokenizer: lambda { |str| str.split(/\s+/) },
      too_short: "must have at least %{count} words",
      too_long: "must have at most %{count} words"
    };

  validates :content, presence: true, length:
    { 
     minimum: 10, 
     maximum: 50,
     tokenizer: lambda { |str| str.split(/\s+/) },
     too_short: "must have at least %{count} words",
     too_long: "must have at most %{count} words"
    };
 

    
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
  end

  def new
    @subject = Subject.find(params[:subject_id])
  end

  def create
    @subject = Subject.find(params[:subject_id])
    @new_topic = Topic.new(topic_params)
    @new_topic.update_attributes(:subject_id => @subject.id)
    if @new_topic.save
      redirect_to subject_groups_path(@subject)
    else
      flash[:error] = @new_topic.errors.full_messages.to_sentence
      redirect_to subject_groups_path(@subject)
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :content)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/create.html.erb
<h1>Topics#create</h1>
<p>Find me in app/views/topics/create.html.erb</p>

app/views/topics/delete.html.erb
<h1>Topics#delete</h1>
<p>Find me in app/views/topics/delete.html.erb</p>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<h1>Topics#index</h1>
<p>Find me in app/views/topics/index.html.erb</p>

app/views/topics/new.html.erb
<!-- <h1>Topics#new</h1> -->
<!-- <p>Find me in app/views/topics/new.html.erb</p> -->

<%= simple_form_for Topic.new, :url => subject_topics_path do |f| %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-9">
        <form>
          <div class="form-group">
            <label class="create-form" for="topic-title-input">Topic Title</label>
            <%= f.input :title, placeholder: "Enter topic title here", label: false %>
            <label class="create-form" for="topic-content-input">Topic Content</label>
            <%= f.input :content, placeholder: "Enter topic content here", label: false %>
          </div>
        </form>
        <%= f.button :submit %>
        <%= link_to "Cancel", subject_groups_path(@subject), {:class => "btn btn-warning"} %>
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
<% end %>

app/views/topics/show.html.erb
<h1>Topics#show</h1>
<p>Find me in app/views/topics/show.html.erb</p>

app/views/topics/update.html.erb
<h1>Topics#update</h1>
<p>Find me in app/views/topics/update.html.erb</p>