config/routes.rb
Rails.application.routes.draw do

  resources :subjects do |s|
    member do
      get :activate
      get :deactivate
    end
    resources :groups do |g|
      resources :instructor_answers
      resources :posts do |p|
        resources :discussions
      end
    end
    resources :topics
  end
  root to: 'subjects#index'
  devise_for :users
  resources :users

end

app/models/group.rb
class Group < ActiveRecord::Base
  serialize :student_list,Array

  has_one:topic
  has_many :posts
  has_one :instructor_answer
  belongs_to :Subject

  validates :name, presence: true, length: 
    { 
      minimum: 1, 
      maximum: 20,
      tokenizer: lambda { |str| str.split(/\s+/) },
      too_short: "must have at least %{count} words",
      too_long: "must have at most %{count} words"
    };

  validates :topic_id, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @subject = Subject.find(params[:subject_id])
    @instructors = @subject.instructor_list
    @groups = Group.where(subject_id: @subject.id)
    @topics = Topic.where(subject_id: @subject.id)
  end

  def show
    @subject = Subject.find(params[:subject_id])
    @group = Group.find(params[:id])
    @topic = Topic.find(@group.topic_id)
    @posts = Post.where(group_id: @group.id)
  end

  def new
    @subject = Subject.find(params[:subject_id])
    if @subject.topics.length == 0
      flash[:error] = "Please create topics first"
      redirect_to subject_groups_path(@subject)
    end
    if @subject.topics.length != 0 and @subject.topics.length == @subject.groups.length
      flash[:error] = "Please create more topics"
      redirect_to subject_groups_path(@subject)
    end
  end

  def create
    @subject = Subject.find(params[:subject_id])
    @topic = Topic.find_by(id: params[:group][:topic_id])
    @new_group = Group.new(group_params)
    @new_group.update_attributes(:subject_id => @subject.id)
    if @new_group.save
      @topic.update_attributes(:group_id => @new_group.id)
      redirect_to subject_groups_path(@subject)
    else
      flash[:error] = @new_group.errors.full_messages.to_sentence
      redirect_to subject_groups_path(@subject)
    end
  end

  def edit
  end

  def update
    @subject = Subject.find(params[:subject_id])
    @group = Group.find(params[:id])
    @group.student_list.push(current_user.id)
    if @group.save
      redirect_to subject_group_posts_path(@subject, @group)
    else
      flash[:error] = @group.errors.full_messages.to_sentence
      redirect_to subject_group_path(@subject, @group)
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @subject = Subject.find(params[:subject_id])
    @group.destroy
    redirect_to subject_groups_path(@subject)
  end

  private

  def group_params
    params.require(:group).permit(:name, :topic_id)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/create.html.erb
<h1>Groups#create</h1>
<p>Find me in app/views/groups/create.html.erb</p>

app/views/groups/delete.html.erb
<h1>Groups#delete</h1>
<p>Find me in app/views/groups/delete.html.erb</p>

app/views/groups/edit.html.erb
<h1>Groups#edit</h1>
<p>Find me in app/views/groups/edit.html.erb</p>

app/views/groups/index.html.erb
<!--<h1>Groups#index</h1> -->
<!-- <p>Find me in app/views/groups/index.html.erb</p> -->

<ol class="breadcrumb">
  <li><a href="#"><%=link_to "Courses", subjects_path %></a></li>
  <li><a href="#"><%= @subject.name %></a></li>
  <li class="active">Topics & Groups</li>
</ol>

<% if @subject.active_status == false %>
  <p><b>This class has been made inactive by instructor</b></p>
<% end %>

<% if current_user.is_instructor == true %>
  <div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="CourseActiondropdownMenu" data-toggle="dropdown" aria-expanded="true">
      Actions
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
      <% if @subject.active_status == true %>
        <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><%= link_to "Create Group", new_subject_group_path(@subject) %></a></li>
        <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><%= link_to "Create Topic", new_subject_topic_path(@subject) %></a></li>
        <li role="presentation" class="divider"></li>
      <% end %>
      <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><%= link_to "Activate", activate_subject_path(@subject) %></a></li>
      <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><%= link_to "Deactivate", deactivate_subject_path(@subject) %></a></li>
    </ul>
  </div>
<% end %>


<!--Group show modals -->
<% @groups.each do |g| %>
  <div class="modal fade group-modal" id="group-<%= g.id %>-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="group"+"<%= g.id %>"+"-modal-title"> <%= g.name %> <small><%= g.topic.title %></small></h4>
        </div>
        <div class="modal-body" id="group"+"<%= g.id %>"+"-modal-body">
          <%= g.topic.content %>
        </div>
        <div class="modal-footer">
          <% if current_user.is_instructor == true %>
              <%= link_to "Watch", subject_group_posts_path(@subject, g), {:class => "btn btn-default"} %>
              <button class="btn btn-warning">
                <%= link_to "Delete", subject_group_path(@subject, g), :method => :delete %>
              </button>
          <% else %>
            <% if !(g.student_list.include? current_user.id) %>
                <button class="btn btn-default">
                  <%= link_to "Join", subject_group_path(@subject, g), :method => :patch %>
                </button>
            <% else %>
              <%= link_to "Go", subject_group_posts_path(@subject, g), {:class => "btn btn-primary"} %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<!-- Topic Container -->
<div id="topic-container" class="container-fluid">
    <div class="row">
      <div class="page-header">
        <h1> Topics <small>for group discussion</small></h1>
      </div>
      <!-- Topic panel -->
      <% @topics.each do |t| %>
        <div class="col-lg-3 course-panel-container">
          <div class="panel panel-primary course-panel hvr-buzz-out">
            <div class="panel-heading course-panel-heading">
              <%= t.title %>
            </div>
            <div class="panel-body">
              <p>
                <%= t.content %>
              </p>
            </div>
          </div>
        </div>
      <% end %>
      <!-- Topic panel! -->
    </div>
</div>


<!-- Group Container -->
<div id="group-conatiner" class="container-fluid">
    <div class="row">
      <div class="page-header" id="group-header">
        <h1> Groups <small>hover to show topic</small></h1>
      </div>
      <style>
      .page-header {
        margin-top: 20px;
        text-align: center;
      }
      </style>
      <!-- Group panel -->
      <% @groups.each do |group| %>
        <div class="col-lg-3 group-panel-container">
          <div class="panel panel-primary group-panel hvr-bounce-to-right" data-toggle="tooltip" data-placement="top" title="<%= group.topic.title %>">
            <a data-toggle="modal" data-target="#group-<%= group.id %>-modal" href="#">
              <div class="panel-body group-panel-body">
                <%= group.name %>
              </div>
            </a>
          </div>
        </div>
      <% end %>
    </div>
</div>
<!--Group container -->

app/views/groups/new.html.erb
<!-- <h1>Groups#new</h1> -->
<!-- <p>Find me in app/views/groups/new.html.erb</p> -->

<%= simple_form_for Group.new, :url => subject_groups_path do |f| %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-9">
        <form>
          <div class="form-group">
            <label class="create-form" for="group-title-input">Group Name</label>
            <%= f.input :name, placeholder: "Enter group name here", label: false %>
          </div>
          <div class="form-group">
            <label class="create-form" for="group-topic-choice">Available Topics</label>
            <br>
            <%= f.collection_select :topic_id, Topic.where(subject_id: @subject.id).where(group_id: nil), :id, :title %>
          </div>
        </form>
        <%= f.button :submit %>
        <%= link_to "Cancel", subject_groups_path(@subject), {:class=>"btn btn-warning"} %>
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
<% end %>

app/views/groups/show.html.erb
<h1>Groups#show</h1>
<p>Find me in app/views/groups/show.html.erb</p>
<%= @group.name %>
<br>
<%= @topic.title %>
<br>
<%= @topic.content %>
<br>

<% if current_user.is_instructor == false %>
  <% if !(@group.student_list.include? current_user.id) %>
    <%= link_to "Join", subject_group_path(@subject, @group), :method => :patch %>
  <% end %>
<% else %>
  <%= link_to "Watch", subject_group_posts_path(@subject, @group) %>
  <%= link_to "Delete", subject_group_path(@subject, @group), :method => :delete %>
<% end %>

<%= link_to "Back", subjects_path %>

app/views/groups/update.html.erb
<h1>Groups#update</h1>
<p>Find me in app/views/groups/update.html.erb</p>