config/routes.rb
Rails.application.routes.draw do

  resources :subjects do |s|
    member do
      get :activate
      get :deactivate
    end
    resources :groups do |g|
      resources :instructor_answers
      resources :posts do |p|
        resources :discussions
      end
    end
    resources :topics
  end
  root to: 'subjects#index'
  devise_for :users
  resources :users

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :Group
  has_many :discussions

  validates :summary, presence: true, length:
    {
      minimum: 1,
      maximum: 15,
      tokenizer: lambda { |str| str.split(/\s+/) },
      too_short: "must have at least %{count} words",
      too_long: "must have at most %{count} words"
    };
  validates :content, presence: true, length:
    {
      minimum: 5,
      maximum: 300,
      tokenizer: lambda { |str| str.split(/\s+/) },
      too_short: "must have at least %{count} words",
      too_long: "must have at most %{count} words"
    };

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @subject = Subject.find(params[:subject_id])
    #@topic = Topic.find(@group.topic_id)
    @topic = @group.topic
    @posts = Post.where(group_id: @group.id)
    @instructor_answer = @group.instructor_answer
  end

  def show
    @subject = Subject.find(params[:subject_id])
    @group = Group.find(params[:group_id])
    @post = Post.find(params[:id])
    @discussions = Discussion.where(post_id: @post.id)
  end

  def new
  end

  def create
    @group = Group.find(params[:group_id])
    @subject = Subject.find(params[:subject_id])
    @new_post = Post.new(post_params)
    @new_post.update_attributes(:group_id => @group.id, :user_id => current_user.id)
    if @new_post.save
      redirect_to subject_group_post_path(@subject, @group, @new_post)
    else
      flash[:error] = @new_post.errors.full_messages.to_sentence
      redirect_to subject_group_post_path(@subject, @group)
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  
  def post_params
    params.require(:post).permit(:summary, :content)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>
<strong>
  Group:
</strong>
<%= @group.name %>
<br>
<strong>
  Topic:
</strong>
<%= @topic.title %>
<br>
<%= @topic.content %>
<br>
<strong><em>
  Instructor Answer:
</em></strong>
<h4><em>
  <% if @instructor_answer %>
    <%= @instructor_answer.content %>
    <em>
      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp-------------------------<%= User.find(@instructor_answer.user_id).name %>[Instructor]
    </em>
  <% end %>
</em></h4>
<% if current_user.is_instructor == true %>
  <% if @group.instructor_answer_id == nil %>
    <%= simple_form_for InstructorAnswer.new, :url => subject_group_instructor_answers_path(@subject, @group) do |f| %>
      <div>
        <%= f.input :content %>
      </div>
      <br>
      <p>
        <%= f.button :submit %>
      </p>
    <% end %>
  <% end %>
<% end %>

<% @posts.each do |p| %>
  <p>
    <h3>
      <%= link_to p.summary, subject_group_post_path(@subject, @group, p) %>
    </h3>
    <%= p.content %>
    <br>
  </p>
<% end %>

<% if @subject.active_status == true %>
  <%= simple_form_for Post.new, :url => subject_group_posts_path(@subject, @group) do |f| %>
    <div>
      <%= f.input :summary %>
      <%= f.input :content %>
    </div>
    <br>
    <p>
      <%= f.button :submit %>
    </p>
  <% end %>
<% end %>


<%= link_to "Back", subject_groups_path(@subject) %>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>
<p class="lead">
    <%= @post.summary %>
    <%= @post.content %>
    <small>
      <em>
        &nbsp&nbsp&nbsp&nbsp&nbsp--- post by <b><%= User.find(@post.user_id).name %></b>
      </em>
    </small>
</p>
<% if @subject.active_status == true %>
  <%= link_to "Reply", new_subject_group_post_discussion_path(@subject, @group, @post) %>
<% end %>

<br>
<strong>
  Discussions:
</strong>
<br>
<% @discussions.each do |d| %>
 <p>
   <%= d.content %><span>-----------by <%= User.find(d.user_id).name %></span>
   <div>-------------------<div>
 </p>
<% end %>
<%= link_to "Back", subject_group_posts_path(@subject, @group) %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>