config/routes.rb
Rails.application.routes.draw do

  resources :subjects do |s|
    member do
      get :activate
      get :deactivate
    end
    resources :groups do |g|
      resources :instructor_answers
      resources :posts do |p|
        resources :discussions
      end
    end
    resources :topics
  end
  root to: 'subjects#index'
  devise_for :users
  resources :users

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default" id="top-navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Groupify', root_path, class: 'navbar-brand' %>
      <style>
      .navbar-brand {
        float: left;
        font-size: 18px;
        height: 50px;
        padding: 15px 15px;
        line-height: 20px;
      }
      </style>
    </div>
    <nav id="bs-example-navbar-collapse-1" class="collapse navbar-collapse navbar-right">
      <%= render 'layouts/navigation_links' %>
    </nav>
  </nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<ul class="nav navbar-nav navbar-left">
  <li class="navbar-left">
    <a href="#menu-toggle" id="menu-toggle">Toggle Menu</a>
  </li>
</ul>
<ul class="nav navbar-nav">
<% if user_signed_in? %>
  <li class="drop-down">
    <a class="dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-expanded="false">Account<span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li><%= link_to 'Profile', user_path(current_user) %></li>
      <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Sign Out', destroy_user_session_path, :method=>'delete' %></li>
    </ul>
  </li>
  <form class="navbar-form navbar-left" role="search">
    <div class="form-group">
      <input class="form-control" type="text" placeholder="Search for courses...">
    </div>
    <button class="btn btn-default" type="submit">Search</button>
  </form>
<% else %>
  <li><%= link_to 'Sign In', new_user_session_path %></li>
  <li><%= link_to 'Sign Up', new_user_registration_path %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Devise" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div id="wrapper">
      <!-- Sidebar -->
      <div id="sidebar-wrapper">
          <ul class="sidebar-nav">
              <li>
                  <%= link_to "All Courses", root_path %>
              </li>
              <% if current_user %>
                <li>
                    <a href="#">My Courses</a>
                </li>
                <li>
                  <% if current_user.is_instructor == true %>
                    <%= link_to "Create Course", new_subject_path %>
                  <% end %>
                </li>
              <% end %>
              <li>
                  <a href="#" data-toggle="modal" data-target="#contactModal">Contact</a>
              </li>
              <li>
                  <a href="#" data-toggle="modal" data-target="#aboutModal">About</a>
              </li>
          </ul>
      </div>
      <!-- sidebar -->
      <!-- page content -->
      <div class="page-content-wrapper">

        <!-- contact and about modal -->
        <div id="contactModal" class="modal fade" aria-hidden="true" tabindex="-1">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 id="contactModalTitle" class="modal-title">Contact</h4>
              </div>
              <div class="modal-body" id="contact-modal-body">
                Email: junyuw@berkeley.edu<br>
                Location: Berkeley, CA
              </div>
              <style>
              #contact-modal-body {
                text-align: center
              }
              .modal-title {
                text-align: center
              }
              </style>
            </div>
          </div>
        </div>
        <div id="aboutModal" class="modal fade" aria-hidden="true" tabindex="-1">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 id="aboutModalTitle" class="modal-title">About</h4>
              </div>
              <div class="modal-body" id="about-modal-body">
                Lorem ipsum dolor sit amet luctus nulla sodales imperdiet eget in placerat montes a at. Sed sem maecenas. Est pellentesque suscipit urna mollitia interdum. Condimentum turpis velit. At suspendisse sit. Ullamcorper semper quis. Class suspendisse curabitur dui id purus. Aliquet mi semper. Venenatis consequat in donec hendrerit pulvinar molestie at sed. Donec est turpis nunc imperdiet tempora. Et vivamus nonummy gravida porttitor pellentesque. Morbi duis et nulla in in egestas.
              </div>
            </div>
          </div>
        </div>
        <!-- contact and about modal -->
        
        <main role="main">
        <style>
        main {
          margin-top: 0px;
          background: #F8F8F8;
          padding-top: 15px;
        }
        </style>
           <%= render 'layouts/messages' %>
           <%= yield %>
        </main>
      </div>
      <!-- page content -->
    </div>
    <!-- wrapper -->

    <!-- Menu Toggle Script -->
    <script>
    //toggle menu when clicked
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });

    //adjust heights of course-panel when flipped
    $(".course-panel-container").mouseenter(function(e) {
        var heightOfContent = $(this).children().children().children('div.back').height() + 20;
        this.setAttribute("style", "min-height:"+heightOfContent+"px");
    });
    
    $(".course-panel-container").mouseleave(function(e) {
        this.setAttribute("style", "min-height:100px");
    });

    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })

    </script>
    
  </body>
</html>